### ISSUE TITLE
Compatibility OH2 Beta / Karaf

### ISSUE THREAD

**Issue by shorty707** [cdjackson/HABmin2#109]
[WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/OH/addons/org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.0.15.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.ui.habmin [172]
  Unresolved requirement: Require-Bundle: javax.servlet

	at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1207)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:504)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[8:org.apache.felix.fileinstall:3.5.0]

**Comment by Tavalin** [comment]
I managed to fix my binding by including the missing package in the Import-Package section of the MANIFEST.MF like below:

```
 Import-Package: com.google.common.collect,
 org.apache.commons.lang;version="2.6.0",
 org.eclipse.smarthome.config.core,
 org.eclipse.smarthome.config.discovery,
 org.eclipse.smarthome.core.items,
 org.eclipse.smarthome.core.library.types,
 org.eclipse.smarthome.core.thing,
 org.eclipse.smarthome.core.thing.binding,
 org.eclipse.smarthome.core.thing.binding.builder,
 org.eclipse.smarthome.core.types,
 org.osgi.service.component;version="1.2.2",
 javax.xml.bind,
 org.slf4j
```

**Comment by cdjackson** [comment]
Thanks. I’ll update in the next couple of days (am travelling at the moment)…

Cheers
Chris

**Comment by cdjackson** [comment]
This has been updated.
