### ISSUE TITLE
Missing Constraint: Import-Package: org.apache.commons.io; version="2.2.0"

### ISSUE THREAD

**Issue by amateo** [cdjackson/HABmin2#13]
Hi,

I have downloaded openhab (1) and I'm trying to install habmin2. According https://github.com/cdjackson/HABmin2, I have installed zwave jar and habmin2 jar in the addons directory.

Now, when openhab is started, I can see that habmin2 bundle is installed (but not run)
```
osgi> lb habmin
START LEVEL 6
   ID|State      |Level|Name
  227|Installed  |    1|HABmin User Interface (2.0.0.201503081445)
```
but if I try to run it, it fails:
```
osgi> start 227
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at org.eclipse.equinox.console.commands.EquinoxCommandsConverter.convert(EquinoxCommandsConverter.java:61)
	at org.apache.felix.gogo.runtime.CommandProcessorImpl.convert(CommandProcessorImpl.java:254)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.convert(CommandSessionImpl.java:374)
	at org.apache.felix.gogo.runtime.Reflective.coerce(Reflective.java:389)
	at org.apache.felix.gogo.runtime.Reflective.coerce(Reflective.java:310)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:110)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Console.run(Console.java:62)
	at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)
	at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
	at java.lang.Thread.run(Thread.java:745)
gogo: BundleException: The bundle "org.openhab.ui.habmin_2.0.0.201503081445 [227]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.io; version="2.2.0"
```
Any help? Thank you.

**Comment by cdjackson** [comment]
I'm travelling at the moment but will take a look at this tomorrow. 

Chris

**Comment by cdjackson** [comment]
I've not managed to work out what bundle is exporting this package. Are you running a recent version of OH2?

**Comment by amateo** [comment]
I'm running OH (1)

**Comment by cdjackson** [comment]
Ah - you might be using the wrong JAR. You need to install the JARs from the openhab1 site - both the habmin and zwave JARs.

https://github.com/cdjackson/HABmin2#openhab-1

**Comment by amateo** [comment]
But then, it is habmin (1), isn't it?

**Comment by cdjackson** [comment]
No.  There are 2 parts to HABmin. The JAR - this provides the interface to openhab, and the client side that provides the user interface. Most of the changes are in the user interface - the JAR is providing the interface into the core, and this changes to support the different versions.

**Comment by amateo** [comment]
I'll have reinstalled everything. It is working fine now.
Thank you.
