### ISSUE TITLE
New z-wave device request - Aeon Labs Smart Switch 6

### ISSUE THREAD

**Issue by xsnrg** [cdjackson/HABmin2#51]
Device: Aeotec Smart Switch 6
Manufacturer: Aeon Labs

Manufacturer ID: 86
Device ID: 60
Device Type: 103

Notes:

I was able  to configure it like an individual port on the 6 port Aeotec power strip, including meter classes to pull concurrent watts and total kwH.  In addition the manual is sparse, but they did include this tidbit:  Parameter 81 (1 byte dec) can be used to change between 3 LED modes.  0=Energy Mode, 1=Momentary Indicate Mode, 2=Night Light Mode

//Aeotec Smart Switch 6
Switch Smart6  "Smart6" <energy> (outlets) {zwave="6:0:command=switch_binary" }
    Number Smart6_Power "Smart6 power  [%.2f W]" (power) {zwave="6:0:command=meter,meter_scale=E_W,refresh_interval=30" }
    Number Smart6_Energy "Smart6 consumption  [%.2f KWh]" (power) {zwave="6:0:command=meter,meter_scale=E_KWh,refresh_interval=30" }
Number Smart6_Volts		"Smart6 voltage [%.2f V]"			(All,power)		{zwave="6:0:command=meter,meter_scale=E_V,refresh_interval=30"}
Number Smart6_Amps		"Smart6 amperage [%.2f A]"			(All,power)		{zwave="6:0:command=meter,meter_scale=E_A,refresh_interval=30"}

I do not have the engineering doc yet.  It is only a coincidence that it is device #6 on my zwave network :)

Jim

2015-05-28 21:09:19.897 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class ZWAVE_PLUS_INFO
2015-05-28 21:09:19.897 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class SWITCH_ALL
2015-05-28 21:09:19.898 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class CLOCK
2015-05-28 21:09:19.898 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class ASSOCIATION_GROUP_INFO
2015-05-28 21:09:19.899 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class FIRMWARE_UPDATE_MD
2015-05-28 21:09:19.899 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class POWERLEVEL
2015-05-28 21:09:19.966 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class ZWAVE_PLUS_INFO
2015-05-28 21:09:19.967 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class SWITCH_ALL
2015-05-28 21:09:19.967 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class CLOCK
2015-05-28 21:09:19.967 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class ASSOCIATION_GROUP_INFO
2015-05-28 21:09:19.968 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class FIRMWARE_UPDATE_MD
2015-05-28 21:09:19.968 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 6: Unsupported command class POWERLEVEL
2015-05-28 21:09:21.931 [WARN ] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 6: Node advancer: SET_ASSOCIATION - Unknown device: 86:103:60
2015-05-28 21:09:22.038 [WARN ] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 6: Node advancer: GET_CONFIGURATION - Unknown device: 86:103:60
2015-05-28 21:09:22.183 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 6: No item bound for event, endpoint = 0, command class = SWITCH_BINARY, value = 0, ignoring.
2015-05-28 21:09:22.392 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 6: No item bound for event, endpoint = 0, command class = METER, value = 0E+1, ignoring.
2015-05-28 21:09:22.623 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 6: No item bound for event, endpoint = 0, command class = METER, value = 123.597, ignoring.
2015-05-28 21:09:22.832 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 6: No item bound for event, endpoint = 0, command class = METER, value = 0.016, ignoring.
2015-05-28 21:09:23.052 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 6: No item bound for event, endpoint = 0, command class = METER, value = 0E+1, ignoring.

**Comment by xsnrg** [comment]
Is it possible to attach docs to a github ticket, or only images?  This is one of the Aeotec devices that we have docs for.  With the folks offering to help with bindings, it would be nice to be able to attach engineering docs.

**Comment by xsnrg** [comment]
Chris, I finally have time to learn how to create these and work my own tickets.  I do have a few questions about the format of the database though if you don't mind.

1) Can I add a label to the Command class entries in the xml without affecting the operation of the binding?  That is, I would like to have the manufacturer's description as part of the xml.  This seems to be handy for people, including myself, to learn and have a reference as new command classes come about. -- Nevermind, I think I just saw the comment attribute which would work for this.

2) following up from 1) above, I would like to add all of the command classes that I can map to the HEX value to the xml.  This means the xml will have more data defined than the binding knows how to handle today.  This should future proof the database entry if/when the binding supports new command classes.  Can we do this without affecting the operation of the binding today?  Z-wave plus command classes are a good example of this I think.

Combining 1 and 2 above would give a new XML entry for this particular switch that looks something like this:

		<Class>
			<id>0x5E</id>
		</Class>

Thanks!
Jim

**Comment by xsnrg** [comment]
OK, 1 above completely answered.  Other device entries have the comment in use.  It was, of course, only the ones I chose to reference that did not have comments.

**Comment by cdjackson** [comment]
Hi jim,
I wouldn’t worry too much about the command classes. The binding doesn’t use this information except in special cases… For OH2, the database will be a different format (I will convert automatically) and this information will not be the same, so it’s not worth worrying about… That said, if you really want to add it, then it won’t do any harm…

Chris

**Comment by xsnrg** [comment]
Pull request created.  https://github.com/openhab/openhab/pull/2871

**Comment by xsnrg** [comment]
@cdjackson , thanks for the merge.  Unfortunately, in doing some further testing, I stumbled across something I don't understand yet, and it is causing an error with the new device configuration that was merged.

I am getting this exception:

2015-07-08 16:05:05 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 6: SendData Request. CallBack ID = 26, Status = Transmission complete and ACK received(0)
2015-07-08 16:05:05 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63   ] - Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 06 03 70 05 53 
2015-07-08 16:05:05 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64   ] - Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 1A 00 00 0D 
2015-07-08 16:05:05 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65   ] - Checking transaction complete: class=SendData, expected=ApplicationCommandHandler, cancelled=false
2015-07-08 16:05:05 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 0D 00 04 00 06 07 70 06 53 03 1B 14 1B C5 
2015-07-08 16:05:05 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
2015-07-08 16:05:05 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
2015-07-08 16:05:05 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 0D 00 04 00 06 07 70 06 53 03 1B 14 1B C5 
2015-07-08 16:05:05 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 0D 00 04 00 06 07 70 06 53 03 1B 14 1B C5 
2015-07-08 16:05:05 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 06 07 70 06 53 03 1B 14 1B 
2015-07-08 16:05:05 [DEBUG] [ApplicationCommandMessageClass:38   ] - NODE 6: Application Command Request (ALIVE:GET_CONFIGURATION)
2015-07-08 16:05:05 [DEBUG] [ApplicationCommandMessageClass:56   ] - NODE 6: Incoming command class CONFIGURATION
2015-07-08 16:05:05 [DEBUG] [ZWaveConfigurationCommandClass:76   ] - NODE 6: Received Configuration Request
2015-07-08 16:05:05 [DEBUG] [ZWaveConfigurationCommandClass:115  ] - NODE 6: Node configuration report, parameter = 83, value = 1774619
2015-07-08 16:05:05 [ERROR] [b.z.i.protocol.ZWaveController:1220 ] - Exception during Z-Wave thread: Input.java.lang.IllegalArgumentException: illegal parameter size
        at org.openhab.binding.zwave.internal.protocol.ConfigurationParameter.<init>(ConfigurationParameter.java:38)
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass.processConfigurationReport(ZWaveConfigurationCommandClass.java:123)
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass.handleApplicationCommandRequest(ZWaveConfigurationCommandClass.java:88)
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:80)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:221)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:194)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:189)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1213)

parameter 83 is set to byte, with a size 3.  When the configuration is coming back from the device, a value of 1774619 is getting dropped in, which corresponds to 1B141B in hex.  Is it trying to store this decimal as a hex, meaning the size won't work?

The parameter information comes from the engineering doc.

**Comment by cdjackson** [comment]
I’ll take a look at the exception, but are you sure that size should be 3 and not 4? I’m just trying to thing if it’s allowed to be 3 - I had a feeling it had to be 1, 2, or 4...

**Comment by cdjackson** [comment]
Yes - this is thrown because the parameter size isn’t 1,2 or 4… 

The device is reporting this, so it must be correct. I’ll need to update the binding to fix this. I’ll try and do it tonight...

**Comment by cdjackson** [comment]
Grab the next snapshot - hopefully it will fix this issue...

**Comment by xsnrg** [comment]
Created another pull request.  Found I had only identified one of four possible location based IDs.  This adds the other 3 types.  Also, the latest snapshot did fix the exception and the device is working better.  There still seems to be a problem in Habmin2 where the lists are not populating correctly with the options?

Parameter 3 looks like the below in the XML, but see the attached image for what my Habmin2 looks like.  Either that or something is still wrong with my XML that I have not found yet.  Will try another debug run.

Jim
![zw096](https://cloud.githubusercontent.com/assets/1186921/8587616/f99ad610-25c3-11e5-9038-dee327080ba7.png)


```
<Parameter>
            <Index>3</Index>
            <Type>list</Type>
            <Size>1</Size>
            <Default>0</Default>
			<Item>
				<Value>0</Value>
				<Label lang="en">disabled</Label>
			</Item>
			<Item>
				<Value>1</Value>
				<Label lang="en">enabled</Label>
			</Item>
            <Label lang="en">Current overload protection enable</Label>
            <Help lang="en">Current Overload Protection. Load will be closed when the 
                Current overrun (US: 15.5A, other country: 16.2A) and the 
                time more than 2 minutes (0=disabled, 1=enabled).
            </Help> 
        </Parameter>

**Comment by cdjackson** [comment]
I guess we're good to close this now?

**Comment by xsnrg** [comment]
Yes, and thank you.

**Comment by cdjackson** [comment]
No probs - thanks.
